### ISSUE TITLE
Question's

### ISSUE THREAD

**Issue by Miya25** [DiscordBio/dbio.me#1]
Hey team thank's for reviewing this. I have few question's to ask.

• Is there any restriction's to self host this for public website purposes?
• Does the code have any backend?
• what will happen if some person self host the site and use it for there site by doing some
modification's and giving credit's

Thanks!

**Comment by clqu** [comment]
We decided to share it just so people can get something and Yes it has a backend.
https://github.com/DiscordBio/api.dbio.me

**Comment by Miya25** [comment]
can people use it for there site?
